In [1]:
import numpy as np 

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.datasets import load_digits
digits = load_digits()

In [2]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [4]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test,y_test)

C:\Users\BASHA\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9703703703703703

In [5]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test,y_test)

0.9944444444444445

In [6]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9740740740740741

In [7]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [9]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [10]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9944444444444445

In [11]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [16]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    
    scores_lr.append(get_score(LogisticRegression(),X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(),X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train, X_test, y_train, y_test))

C:\Users\BASHA\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\BASHA\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [17]:
scores_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [18]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [19]:
scores_rf

[0.9265442404006677, 0.9482470784641068, 0.9198664440734557]

In [20]:
from sklearn.model_selection import cross_val_score

In [21]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

C:\Users\BASHA\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\BASHA\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [22]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [23]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.93611111, 0.92222222, 0.95543175, 0.9637883 , 0.92200557])

In [24]:
cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target)

array([0.85833333, 0.81111111, 0.85793872, 0.8913649 , 0.82451253])

In [25]:
cross_val_score(RandomForestClassifier(n_estimators=15), digits.data, digits.target)

array([0.91388889, 0.90833333, 0.94150418, 0.93871866, 0.89972145])

In [26]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target) # paramter tuning

array([0.92777778, 0.89722222, 0.95821727, 0.96657382, 0.92479109])

In [27]:
cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target)

array([0.93055556, 0.91111111, 0.94986072, 0.9637883 , 0.93871866])

In [28]:
cross_val_score(RandomForestClassifier(n_estimators=60), digits.data, digits.target)

array([0.93333333, 0.9       , 0.96100279, 0.95821727, 0.94150418])